//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallotBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BallotBox()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int BallotBoxId { get; set; }
        public Nullable<int> BallotBoxNumber { get; set; }
        public Nullable<int> NeighbourhoodId { get; set; }
        public Nullable<int> VoterCount { get; set; }
    
        public virtual Neighbourhood Neighbourhood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
