//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int PartyId { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> PresidentId { get; set; }
        public string Founder { get; set; }
        public Nullable<System.DateTime> FoundationDate { get; set; }
        public Nullable<int> HeadquartersId { get; set; }
        public Nullable<bool> IsParty { get; set; }
    
        public virtual President President { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
