//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteId { get; set; }
        public Nullable<int> BallotBoxId { get; set; }
        public Nullable<int> PartyId { get; set; }
        public int VoteCount { get; set; }
    
        public virtual BallotBox BallotBox { get; set; }
        public virtual Party Party { get; set; }
    }
}
